project_id = "prwecptqgyjzxsjnqojt"

[functions.notify-enquiry]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.admin-photos]
verify_jwt = false