/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingPolicyRouteImport } from './routes/booking-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesSlugRouteImport } from './routes/properties_.$slug'

const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPolicyRoute = BookingPolicyRouteImport.update({
  id: '/booking-policy',
  path: '/booking-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties_/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-policy': typeof BookingPolicyRoute
  '/contact': typeof ContactRoute
  '/guide': typeof GuideRoute
  '/properties': typeof PropertiesRoute
  '/properties/$slug': typeof PropertiesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-policy': typeof BookingPolicyRoute
  '/contact': typeof ContactRoute
  '/guide': typeof GuideRoute
  '/properties': typeof PropertiesRoute
  '/properties/$slug': typeof PropertiesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-policy': typeof BookingPolicyRoute
  '/contact': typeof ContactRoute
  '/guide': typeof GuideRoute
  '/properties': typeof PropertiesRoute
  '/properties_/$slug': typeof PropertiesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-policy'
    | '/contact'
    | '/guide'
    | '/properties'
    | '/properties/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-policy'
    | '/contact'
    | '/guide'
    | '/properties'
    | '/properties/$slug'
  id:
    | '__root__'
    | '/'
    | '/booking-policy'
    | '/contact'
    | '/guide'
    | '/properties'
    | '/properties_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingPolicyRoute: typeof BookingPolicyRoute
  ContactRoute: typeof ContactRoute
  GuideRoute: typeof GuideRoute
  PropertiesRoute: typeof PropertiesRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-policy': {
      id: '/booking-policy'
      path: '/booking-policy'
      fullPath: '/booking-policy'
      preLoaderRoute: typeof BookingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties_/$slug': {
      id: '/properties_/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingPolicyRoute: BookingPolicyRoute,
  ContactRoute: ContactRoute,
  GuideRoute: GuideRoute,
  PropertiesRoute: PropertiesRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
